Stop trying unsuccessfully to remove corrosion
It's needed by cxx-rust-cssparser:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: removing corrosion breaks dependency 'corrosion' required by kde-banana-cxx-rust-cssparser-git
```